name: CI-CD


on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC remote auth (DagsHub)
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user mepaluttam
          dvc remote modify origin --local password $DAGSHUB_TOKEN

      - name: DVC Pull
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: dvc pull

      - name: Test Model Registry
        run: pytest tests/test_model_registry.py

      - name: Test Model Performance
        run: pytest tests/test_model_performance.py

      - name: Promote Model
        if: success()
        run: python scripts/promote_model_to_prod.py
