name: CI-CD

on: push

jobs:
  Testing:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Install DVC
        uses: iterative/setup-dvc@v1

      - name: Configure DVC remote auth (DagsHub)
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user mepaluttam
          dvc remote modify origin --local password $DAGSHUB_TOKEN

      - name: DVC Pull
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: dvc pull

      - name: Test Model Registry
        run: pytest tests/test_model_registry.py

      - name: Test Model Performance
        run: pytest tests/test_model_performance.py

      - name: Promote Model
        if: success()
        run: python scripts/promote_model_to_prod.py
